import streamlit as st
from PIL import Image
from ultralytics import YOLO

# Load your YOLO model
model = YOLO('best.pt')

def classify_image(image):
    results = model(image, conf=0.25, imgsz=640)  # Run inference
    first_result = results[0]  # Get the first result


    return first_result.probs.top1  





st.title("AI or Real art?")

st.write("**Upload an image of any art piece and let's try to guees if it was generated by AI or if it is a real art**")

uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Open the image file
    image = Image.open(uploaded_file)
    
    # Display the image
    st.image(image, caption='Uploaded Image.', use_container_width=True)
    st.write("")
 
    
    # Get the classification
    label = classify_image(image)
    
    # Display the classification
    if label == 1:
        st.write("The model prediction is: **Real art (might not be the original painting)**")
    elif label == 0:
        st.write("The model prediction is: **AI generated**")
        
